### ISSUE TITLE
Feature: Take os.loadavg() into account

### ISSUE THREAD

**Issue by addaleax** [piscinajs/piscina#47]
It would be nice if `piscina` took `os.loadavg()` into account when deciding how many workers to use in a given situation, to dynamically respond to the system load. This can be helpful considering that the application that uses `piscina` may not be the main application running on a given host, and that the up to `1.5 × number of CPUs` `maxThreads` default may be too much in a lot of circumstances.

The idea here is that we would not post new tasks until either less than `minThreads` tasks are currently running or the system drops below x CPU load (where x could be e.g. 100 % by default, but configurable).

In a similar vein, it would be nice to be able to set scheduling paramters for the spawned threads, but that would require upstream support in libuv first, then in Node.js, then here.

**Comment by jasnell** [comment]
Love it. 

Let's open a separate thread on the scheduling.

**Comment by jasnell** [comment]
@addaleax on this... there are two ways we could do this:

1. Prevent `runTask()` from queuing additional tasks while the 1-min CPU load is over the threshold (handled as an error just like when we exceed maxQueue), or

2. Allow tasks to continue to be queued but defer allowing a thread to pick up a new pending task if the CPU load is over the threshold, allowing it to go idle unless we are < minThreads.

I *think* option 2 is the one you had in mind but I want to make sure.

**Comment by addaleax** [comment]
Yes, option 2 is what I’m having in mind.

**Comment by jasnell** [comment]
Think we're going a different direction with this so going to close this issue. Will reopen it if necessary
