### ISSUE TITLE
question: can we make piscina available on the web?

### ISSUE THREAD

**Issue by tuananh** [piscinajs/piscina#75]
since web worker is available on the web, can we make piscina available on the web too ?

**Comment by jasnell** [comment]
*Possibly* ... there are quite a few differences between Node.js workers and Web workers but many of the basic concepts hold. What may be easiest would be a separate `piscina-web` module that implements as much of the API as consistently as possible.

**Comment by mcollina** [comment]
My starting question is.. what would you need it for on the Web? Could you please describe your use case?

**Comment by tuananh** [comment]
> My starting question is.. what would you need it for on the Web? Could you please describe your use case?

Eg: Serverless offering like cloudflare workers can only use modules that works on the web (via webpack)

**Comment by mcollina** [comment]
Are you sure you can use Web Workers inside a cloudflare Service Worker? Can you link some docs?

More importantly, what would be the use case for doing so?

**Comment by tuananh** [comment]
I was assuming it can use any npm module that is not Node specific. I cant find any docs via quick google search. I will try later today. 

Another use case would be offloading computation expensive task from main thread.

**Comment by jasnell** [comment]
Going to leave this open a feature request. There are definitely some possibility here but *most likely* this would need to be implemented as a completely separate module.

**Comment by eligrey** [comment]
I made a basic web worker thread pool for browsers as part of [Penumbra](https://github.com/transcend-io/penumbra/blob/master/src/workers.ts).

**Comment by dusty-phillips** [comment]
As far as use case goes, we are building a (I know it sounds crazy) crypto miner intended to run on node and in browser. Piscina is working great on node, and it would be nice to have in the browser with same API as well.

For some people looking for this, threads.js **may** be a cross-platform option, but it is not nearly so ergonomic as piscina, and it completely failed in the face of our WASM code.

**Comment by SouthernPL** [comment]
> 我假设它可以使用任何非 Node 特定的 npm 模块。我无法通过快速谷歌搜索找到任何文档。我今天晚些时候试试。
> 
> 另一个用例是从主线程卸载计算成本高的任务。

i need too!!!
